# Generated by Django 5.0.4 on 2024-05-12 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pregunta', models.CharField(max_length=100, unique=True)),
                ('primera_opcion', models.CharField(max_length=90)),
                ('segunda_opcion', models.CharField(max_length=90)),
                ('tercera_opcion', models.CharField(max_length=90)),
                ('cuarta_opcion', models.CharField(max_length=90)),
                ('opcion_correcta', models.CharField(max_length=90)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.categoriaquiz')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
